### ISSUE TITLE
Not working for code.yandex-team.ru

### ISSUE THREAD

**Issue by belonesox** [fregante/GhostText#206]
Browser: 
* Firefox
* Google Chrome

Editor: 
* VSCode 

# Description
* Trying connect online pad code.yandex-team.ru with ghosttext
* Sync «Browser → VSCode» OK
* Sync «VSCode → Browser» absolute nonsense.

See anigif.
![bug-code avi](https://user-images.githubusercontent.com/1609739/113903694-e9bb5d80-97d9-11eb-9939-febfe9fcd7ab.gif)

**Comment by fregante** [comment]
That URL isn't public so there's nothing I can do about. It appears to be a CodeMirror field and it should work, I don't know why that happens.

**Comment by belonesox** [comment]
> That URL isn't public so there's nothing I can do about it. 

May be something wrong happened.

URL/service is public, I just created a room
https://code.yandex-team.ru/b00dda88-2737-4b5b-a63d-0bbe110948c6
and tested it from different IP/proxies.

![image](https://user-images.githubusercontent.com/1609739/114623364-d7e52900-9cb7-11eb-98e5-0d7ab29c8483.png)

**Comment by fregante** [comment]
Thank you for the link! I just tried it and it looks like the editor is buggy there, it should be fixed by Yandex.

For example, if you press ctrl+a to select everything, the selection is lost immediately. GhostText relies on this feature to select everything and replace it, that's why the text is just appended instead of being replaced.

**Comment by fregante** [comment]
![gif](https://user-images.githubusercontent.com/1402241/115156555-f29c1100-a0ae-11eb-95cd-c169743b094a.gif)

**Comment by belonesox** [comment]
>For example, if you press ctrl+a to select everything, the selection is lost immediately. 

What browser?
I just checked this with Firefox & Chrome, and cannot confirm. "Ctrl-a" selection works OK.

But the bug still persists.

**Comment by fregante** [comment]
Every browser. This is Chrome. You can see that the first time I press ctrl+a it's reset, and maybe the next one stays… until the content is updated. 

![gif](https://user-images.githubusercontent.com/1402241/115235143-0cd3fe80-a144-11eb-9483-d83a524eded8.gif)

**Comment by fregante** [comment]
I just checked my code and it's using the simplest API possible, it's a plain `.setValue` call that should just replace the whole field’s content. I'm not manually selecting and replacing it like I said previously

https://github.com/fregante/GhostText/blob/ad87dffac1e1355e44e7c240a5e571575280b7af/source/unsafe-messenger.js#L47

My guess is that they hacked the CodeMirror code to implement concurrent multi-user edits, so it broke the regular API. A solution could be to transfer just the specific changed text from the editor, but that requires a rewrite of GhostText and that's not happening anytime soon, unfortunately.

**Comment by belonesox** [comment]
> Every browser. This is Chrome. You can see that the first time I press ctrl+a it's reset, and maybe the next one stays… until the content is updated.
> 
Hmm. Something strange. I never see that «Ctrl-a reset» in browser window.
See the demo with  pure Chrome (Google Chrome 89.0.4356.6 dev) with no extensions except GhostText:

https://vimeo.com/453011419/b1d25fbd3c 

>My guess is that they hacked the CodeMirror code to implement concurrent multi-user edits, so it broke the regular API. 

May be, but I cannot reproduce and report «Ctrl-A bug» for them…
